# Generated by Django 5.1.2 on 2024-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huellauser',
            name='is_protectora',
        ),
        migrations.AddField(
            model_name='huellauser',
            name='is_protector',
            field=models.BooleanField(default=False, help_text='Marcar si es una protectora'),
        ),
    ]
