# Generated by Django 5.1.2 on 2024-12-08 16:46

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huellapp', '0002_remove_messageha_recipient_alter_messageha_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='protector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huellapp.protector'),
        ),
        migrations.AlterField(
            model_name='protector',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
